version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: psouza0/gerador-partidas-ea-fc25
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
