version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gerador-partidas-ea-fc
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
